export interface ledgerParamsData {
    status?: string,
    journal_module_id?: any,
    date_from?: any,
    date_to?: any,
    statement?: any,
    father_id?: any,
    student_id?: any,
    cost_center_id?: any,
    cost_center_branch_id?: any,
    cost_center_region_id?: any,
    tag?: any,
    account_guide_id?: any,
    currency_id?: any,
    account?: any,
}
